HousingManagementSystem/Models/Home/CityModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HousingManagementSystem.Models.Home
{
    public class CityModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

HousingManagementSystem/Models/Home/FeatureModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HousingManagementSystem.Models.Home
{
    public class FeatureModel
    {
        public string Name { get; set; }
    }
}

HousingManagementSystem/Models/Home/HomeModel.cs
using Common.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HousingManagementSystem.Models.Home
{
    public class HomeModel
    {
        public HomeModel()
        {
            Cities = new List<City>();
            Featuries = new List<Feature>();
        }
       // public List<CityModel> Cities { get; set; }


        public List<City> Cities { get; set; }

        //public List<FeatureModel> Featuries { get; set; }

        public List<Feature> Featuries { get; set; }

    }

  

}

HousingManagementSystem/Controllers/HomeController.cs
using HousingManagementSystem.Models.Home;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HousingManagementSystem.Controllers
{
    public class HomeController : Controller
    {
        private Common.Interface.IHouseService _houseService;
        private Common.Interface.Ilookup _lookup;
        private Common.Interface.IFeatureService _featureRepo;

        public HomeController()
        {
            _houseService = new Services.HouseService();
            _lookup = new LookupService();
            _featureRepo = new Services.FeatureService();
        }
        //
        // GET: /Home/

        public ActionResult Index()
        {
            
           // var houses = _houseService.GetHousesByName("13-D").ToList();
            var cities = _lookup.GetAllCity().ToList();
            var featurews = _featureRepo.GetAllFeatures().ToList();
            var model = new HomeModel
            {
                Cities = cities,
                Featuries = featurews
            };
            //model.Cities = cities,
            //model.Featuries = 
  

            return View(model);
        }


        public ActionResult Add()
        {
            return View();
        }

        public ActionResult Show()
        {
         
            return View();

        }

        public ActionResult Showjson(string data)
        {

            var viewbag = data;

            return PartialView("_SearchHouses");
        }

    }
}

HousingManagementSystem/Controllers/HouseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HousingManagementSystem.Controllers
{
    public class HouseController : Controller
    {
        //
        // GET: /House/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            
            string search = form["search"];
            string city = form["city"];
            bool chkf = false;
            string chkfeature_ = form["chkfeature_"];
            if (chkfeature_ == "false")
            {
                chkf = false;
            }
            else
            {
                chkf = true;
            }
            ViewBag.chkf = chkf;
            ViewBag.search = search;
            ViewBag.city = city; 



            return View();
        }
    }
}

HousingManagementSystem/Controllers/HouseTestController.cs
using Common.Entities;
using Common.Extensions;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace HousingManagementSystem.Controllers
{
    public class HouseTestController : Controller
    {
        private Common.Interface.IHouseService _houseService;
        public HouseTestController()
        {
            _houseService = new Services.HouseService();
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddHouseImage(HttpPostedFileBase file)
        {
            var houseImage = new HouseImage();

            if (file.ContentLength > 0)
            {
               // var filename = Path.GetFileName(file.FileName);

                //var largeImage1 = Image.FromStream(file.InputStream);              

                var largeImage1 = new WebImage(file.InputStream); 
               

                houseImage.HouseId = 12;
                houseImage.LargeImage1 = largeImage1.GetBytes(); //largeImage1.imageToByteArray(Path.GetExtension(file.FileName));

                //var img = new WebImage(file.InputStream);

                //if (img.Width >= 600)
                //{
                //    img.Resize(200, 200);
                //    //img.GetBytes();
                //}

                houseImage.SmallImage1 = largeImage1.GetBytes();
                _houseService.SaveHouseImag(houseImage);
            }


          


            return View();
        }

    }
}

HousingManagementSystem/Controllers/ShowResultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HousingManagementSystem.Controllers
{
    public class ShowResultController : Controller
    {
        //
        // GET: /ShowResult/

        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Showjson(string name)
        {

            var g = name;

            return View();
        }
    }
}

HousingManagementSystem/Views/Home/Index.cshtml
@model HousingManagementSystem.Models.Home.HomeModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layot.cshtml";
    var count = Model.Featuries.Count;
    var reminder = 0;
}

@section head{
    <link href="~/Content/CustomStyleSheet.css" rel="stylesheet" />
    <script src="~/Content/vendor/bootstrap/js/jquery-ui.min.js"></script>
}

@using (Html.BeginForm("Index", "House", FormMethod.Post))
{

<div class="row">
    <div class="homepage-left-menu col-md-9" style="margin-left:-5px">
        <!--- srart paragraph---->
        <div class="row">
            <div class="col-12">
                <div class="paragraph ">
                    <h4 style="color: #2fa873">Holiday home in Finland</h4>
                    <p>
                        At Holiday Homes Finland we have made it easy for you<br />
                        and total holiday homes and apartments from more than
                        <br />
                        30 providers-
                    </p>
                </div>
            </div>
        </div>

        <!--- End paragraph---->

        <!-----Drop down,Date,------>
        <div class="row">
            <div class="col-md-6">

                @*<div class="col">*@
                <h4 style="color: #2fa873">Search holiday home</h4>
                <div class="row margin-top-20">
                    <div class="col-md-6">
                        @Html.TextBox("search", null, new { @class = "form-control", placeholder = "Name", id = "name"})
                    </div>
                </div>
                <div class="row margin-top-20">
                    <div class="col-md-6">
                        @Html.DropDownList("city", new SelectList(@Model.Cities, "Id", "Name"), "Select city", new { @class = "form-control"})
                    </div>
                </div>
                <div class="row margin-top-20">
                    <div class="col-md-6">
                        @Html.TextBox("dateFrom", null, new { @class = "form-control", placeholder = "Date From",id = "dateFrom" })
                    </div>
                </div>
                <div class="row margin-top-20">
                    <div class="col-md-6">
                        @Html.TextBox("dateTo", null, new { @class = "form-control", placeholder = "Date To",id = "dateTo" })
                    </div>
                </div>

            </div>
            <!----- End Drop down,Date,------>

            <!-- Faclities -->
            <div class="col-md-6">
                <h4 style="color: #2fa873">Facilities</h4>

                @foreach (var feature in @Model.Featuries)
                {

                    bool renderRow = reminder % 2 == 0 ? true : false;
                    if (renderRow)
                    { 
                        @:<div class="row" style="margin-left:0px">
                    }
                    <div class="col-md-6">
                        @Html.CheckBox("chkfeature_" + feature.Id, new { @class = "styled", id = "chkfeature_" + feature.Id })
                        <label for="feature" style="font-weight:200;">
                            @feature.Name
                        </label>
                    </div>
                    if (renderRow)
                    { 
                        @:</div>
                    }
                    reminder++;
                }

                <!-- End Faclities -->
            </div>
        </div>




    </div>

    <div class="homepage-right-menu col-md-3">
        <div class="row">
             <div class="col-md-4">
            imgae here
            <img src="~/Content/smiley.jpg" height="66" width="84" />
        </div>
        </div>
       
    </div>
</div>
    
    <div class="row btnContainer">
            <div class="col-md-4">
                <span>72 holiday homes meet your wishes</span>
            </div>
            <div class="col-md-4">
                <input type="submit" class="btn btn-success" value="show houses" id="btnsubmit" name="btnsubmit" />
            </div>
            <div class="col-md-4">
                
            </div>
        </div>

}
 
<div>


<script>
        $(function () {
            $("#dateFrom").datepicker();
            $("#dateTo").datepicker();


        });
</script>


    @{
        Html.RenderPartial("_SearchHouses");
        
        
        }
</div>


@*<script>
    $(function () {
        $("#btnsubmit").click(function () {
            debugger;
            var model = {
                name: $("#name").val(),
                dateFrom: $("#dateFrom").val(),
                dateTo: $("#dateTo").val(),
                city: $("#city Option:Selected").text(),
                ferture: $(":input[type=checkbox]:checked").val()
            }

           var data = popuLateQuery(model)
           
                    $.ajax({
                        Type: "GET",
                        url: "/Home/Showjson",
                        data: data,
                        success: function (response) {
                            console.log("Mydata", response)

                        },
                        error: function () {
                            alert("There was an error. Try again please!");
                        }

                    })
                })
    });
    function popuLateQuery(data) {
        return "Select * from house Where name LIKE " + data.name + "% AND Created LIKE" + data.dateFrom + "WHERE Feature IN " + data.ferture;

    }

</script>*@

HousingManagementSystem/Views/Home/Showjson.cshtml
@{
    ViewBag.Title = "Showjson";
    Layout = "~/Views/Shared/_Layot.cshtml";
}

<h2>Showjson</h2>

HousingManagementSystem/Views/House/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layot.cshtml";
    var feature = ViewBag.chkfeature_;
}

<h2>Index</h2>
<h4>
    Name: @ViewBag.search<br />
    DropDown: @ViewBag.city<br />
    Feature : @ViewBag.chkf
</h4>

HousingManagementSystem/Views/HouseTest/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layot.cshtml";
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm("AddHouseImage", "HouseTest", FormMethod.Post, new { enctype = "multipart/form-data" }))
{ 
     <input type="file" name="file" />
    <input type="submit" name="Submit" id="Submit" value="Upload" />
}

HousingManagementSystem/Views/Shared/_Layot.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @*<meta http-equiv="refresh" content="10" />*@
    @*<meta http-equiv="refresh" content="10; url=http://www.mytoptutorials.com" />*@
    <meta name="keywords" content="rent house, summer house" />
    
    <title>@ViewBag.Title</title>

    @*<link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />*@
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
    <link href="~/Content/css/simple-sidebar.css" rel="stylesheet" />
    <link href="~/Content/css/custom-style.css" rel="stylesheet" />
    <link href="~/Content/vendor/bootstrap/js/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/vendor/bootstrap/js/jquery-ui.css" rel="stylesheet" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/jquery-ui.min.js"></script>

    @RenderSection("head", false)

</head>
<body>
    @RenderSection("section1", false)
        <nav class="navbar navbar-inverse nav-container">
            <div class="container-fluid padding-top-24">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">Logo</a>
                </div>
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#">Hosues</a></li>
                    <li><a href="#">Aboust</a></li>
                    <li><a href="#">Policy</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="glyphicon glyphicon-user"></span>Sign Up</a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-log-in"></span>Login</a></li>
                </ul>
            </div>
        </nav>
    

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav" style="padding-top:5px;">
                <li>
                    <a href="#">Available Weeks</a>
                </li>
                <li>
                    <a href="#">Facilities</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <a href="#menu-toggle" class="btn btn-secondary" id="menu-toggle">Toggle Menu</a>
                <div>
                     @RenderBody()
                </div>
               
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    @* <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>*@


    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });

        
    </script>
</body>
</html>

HousingManagementSystem/Views/Shared/_SearchHouses.cshtml
ssssssssssssssss

HousingManagementSystem/Views/ShowResult/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

HousingManagementSystem/Views/ShowResult/Showjson.cshtml
@{
    ViewBag.Title = "Showjson";
    Layout = "~/Views/Shared/_Layot.cshtml";
}

<h2>Showjson</h2>